export const FETCH_AUTENTICATION = 'FETCH_AUTENTICATION';
export const FETCH_AUTENTICATION_SUCCESS = 'FETCH_AUTENTICATION_SUCCESS';
export const FETCH_AUTENTICATION_FAILURE = 'FETCH_AUTENTICATION_FAILURE';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const FETCH_SESSION = 'SESSION_FETCH_SESSION';
export const FETCH_SESSION_SUCCESS = 'SESSION_FETCH_SESSION_SUCCESS';
export const FETCH_SESSION_FAILURE = 'SESSION_FETCH_SESSION_FAILURE';

export const FETCH_USER_SHIFT = 'FETCH_USER_SHIFT';
export const FETCH_USER_SHIFT_SUCCESS = 'FETCH_USER_SHIFT_SUCCESS';
export const FETCH_USER_SHIFT_FAILURE = 'FETCH_USER_SHIFT_FAILURE';

export const FETCH_ALL_SHIFTS = 'FETCH_ALL_SHIFTS';
export const FETCH_ALL_SHIFTS_SUCCESS = 'FETCH_ALL_SHIFTS_SUCCESS';
export const FETCH_ALL_SHIFTS_FAILURE = 'FETCH_ALL_SHIFTS_FAILURE';

export const POST_SHIFT = 'POST_SHIFT';
export const POST_SHIFT_SUCCESS = 'POST_SHIFT_SUCCESS';
export const POST_SHIFT_FAILURE = 'POST_SHIFT_FAILURE';
