export const FETCH_CAR = 'CAR_FETCH_CAR';
export const FETCH_CAR_SUCCESS = 'CAR_FETCH_CAR_SUCCESS';
export const FETCH_CAR_FAILURE = 'CAR_FETCH_CAR_FAILURE';

export const FETCH_AUTENTICATION = 'AUTENTICATION_FETCH_AUTENTICATION';
export const FETCH_AUTENTICATION_SUCCESS =
  'AUTENTICATION_FETCH_AUTENTICATION_SUCCESS';
export const FETCH_AUTENTICATION_FAILURE =
  'AUTENTICATION_FETCH_AUTENTICATION_FAILURE';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const FETCH_SESSION = 'SESSION_FETCH_SESSION';
export const FETCH_SESSION_SUCCESS = 'SESSION_FETCH_SESSION_SUCCESS';
export const FETCH_SESSION_FAILURE = 'SESSION_FETCH_SESSION_FAILURE';
